// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8rhJkyMIn1dYQnKE28Wcf2wIGMggiJ7E',
    appId: '1:350798162024:web:b0242ec38a15f898c473dd',
    messagingSenderId: '350798162024',
    projectId: 'totale-reussite-7e7a7',
    authDomain: 'totale-reussite-7e7a7.firebaseapp.com',
    storageBucket: 'totale-reussite-7e7a7.appspot.com',
    measurementId: 'G-BEVEDHP125',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5pkdB8eBvDxGhQUo5GhFPz_2eAqsAcmo',
    appId: '1:350798162024:android:4547962c12e61cf6c473dd',
    messagingSenderId: '350798162024',
    projectId: 'totale-reussite-7e7a7',
    storageBucket: 'totale-reussite-7e7a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtEEWynzMfzHms4RwGikbEPhb0kHNGFrw',
    appId: '1:350798162024:ios:152e91f7e9d853b7c473dd',
    messagingSenderId: '350798162024',
    projectId: 'totale-reussite-7e7a7',
    storageBucket: 'totale-reussite-7e7a7.appspot.com',
    iosClientId: '350798162024-i1pajlrf73ei0hl64ickhek7sidvce4t.apps.googleusercontent.com',
    iosBundleId: 'com.archetechnology.totaleReussite',
  );
}
